language: generic

dist: bionic

script:
   # Install dependencies
  - pwd
  - ls
  - sudo apt-get update
  - sudo apt-get install sqlite3
  - echo $JAVA_HOME
  # Install PROJ
  - wget https://download.osgeo.org/proj/proj-6.2.1.tar.gz
  - tar xf proj-6.2.1.tar.gz
  - cd proj-6.2.1
  - ./configure
  - NPROC=$(nproc)
  - make -j${NPROC}
  - sudo make install
  # build PROJ-JNI
  - cd ..
  - mvn package
  - ls
  # tests
  - java --class-path target/proj-1.0-SNAPSHOT.jar example/TransformPoints.java
